#!/usr/bin/env python3
"""Stamp the assertion totals into the docs, from an actual harness run.

Three different numbers were in circulation — README said 646/19, harness/README
said 615/18, HANDOFF said 345/17 — because each was typed by hand at a different
moment and none was ever checked. The README even warned readers to trust the
code over the prose, which is the correct instinct and the wrong fix.

This reads harness/LAST-RUN.txt, which run_harness.sh already generates, and
rewrites the marked stanza in each doc. verify_docs.py then fails if any doc
disagrees with the recorded run, so the numbers cannot drift again.

    python3 harness/stamp_docs.py            # rewrite the stanzas
    python3 harness/stamp_docs.py --check    # exit 1 if any is stale

The markers are HTML comments so they render as nothing:

    <!-- HARNESS-COUNTS -->
    ...generated text...
    <!-- /HARNESS-COUNTS -->
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAST_RUN = ROOT / "harness" / "LAST-RUN.txt"
BEGIN = "<!-- HARNESS-COUNTS -->"
END = "<!-- /HARNESS-COUNTS -->"

TARGETS = [ROOT / "README.md", ROOT / "harness" / "README.md",
           ROOT / "docs" / "HANDOFF.md", ROOT / "START-HERE.md"]


def read_run():
    """-> dict with assertions, suites, skipped, version, engine, when."""
    if not LAST_RUN.is_file():
        sys.exit("harness/LAST-RUN.txt not found — run ./harness/run_harness.sh first.")
    text = LAST_RUN.read_text(encoding="utf-8")

    def grab(pattern, default=""):
        m = re.search(pattern, text)
        return m.group(1).strip() if m else default

    # Suites that reported a summary, and the assertions they reported. Parsed
    # from the aggregate block rather than recomputed, so this can never claim a
    # number the run itself did not produce.
    oks = re.findall(r"^\s+(\S+): ok — (\d+)/(\d+) passed", text, re.M)
    skipped = re.findall(r"^\s+(\S+): SKIPPED", text, re.M)
    total = sum(int(p) for _, p, _ in oks)
    # Parse the FAILURES too. This only read the "ok" lines and then emitted the
    # words "all green" unconditionally, so running it after a run containing
    # failures published a green claim over a red run — the precise class of
    # unverifiable statement this script exists to eliminate.
    problems = re.findall(r"^\s+(\S+): (?:FAIL|ERROR)", text, re.M)
    m = re.search(r"suites with problems:\s*(\d+)", text)
    if m and int(m.group(1)) and not problems:
        problems = [f"{m.group(1)} suite(s)"]

    return {
        "assertions": total,
        "suites": len(oks),
        "names": [n for n, _ in re.findall(r"^\s+(\S+): (ok|FAIL|ERROR|skip)", text, re.M)],
        "skipped": [s for s in skipped],
        "problems": problems,
        "version": grab(r"SKRIBL_VERSION\s+:\s*(\S+)", "unknown"),
        "engine": grab(r"DATABASE_URL class\s+:\s*(\S+)", "unknown"),
        "when": grab(r"(?:Started|Run at|Date)\s*:\s*(.+)", ""),
        "tree": grab(r"Tree SHA-256\s+:\s*(\S+)", "")[:12],
    }


def _headline(run):
    """THREE states, matching what the runner itself reports.

    This decided on `problems` alone, so a run the runner called
    "PASS WITH SKIPS" was published as "all green" — and then, a few lines
    later, the same stanza listed the skipped suites and said a skip is not
    evidence of coverage. The two statements contradicted each other in one
    generated block. It matters now that a bare run expands to every suite: a
    normal SQLite run skips the PostgreSQL suite, and a Chromium without an
    H.264 encoder skips the MP4 suite, so PASS WITH SKIPS is the ORDINARY
    outcome rather than an edge case.
    """
    tail = (f"on {run['engine']} as of {run['version']} "
            f"(tree `{run['tree']}`).")
    if run["problems"]:
        return (f"**RUN NOT GREEN — {len(run['problems'])} suite(s) failed:** "
                f"{', '.join(run['problems'])}. {run['assertions']} assertions "
                f"passed across {run['suites']} suite(s) that did report, {tail}")
    if run["skipped"]:
        return (f"**PASS WITH SKIPS — {run['assertions']} assertions across "
                f"{run['suites']} suites, none failing, "
                f"{len(run['skipped'])} skipped** {tail}")
    return (f"**{run['assertions']} assertions across {run['suites']} suites, "
            f"all green** {tail}")


def stanza(run):
    lines = [
        BEGIN,
        _headline(run),
        "",
        "These totals are generated by `harness/stamp_docs.py` from "
        "`harness/LAST-RUN.txt` — never typed. `verify_docs.py` fails if any doc "
        "disagrees with the recorded run.",
    ]
    if run["skipped"]:
        lines += [
            "",
            f"Skipped in that run: {', '.join(run['skipped'])}. A skipped suite "
            "contributes zero assertions and is not evidence of coverage.",
        ]
    lines.append(END)
    return "\n".join(lines)


def apply(path, text, check):
    body = path.read_text(encoding="utf-8")
    if BEGIN not in body:
        return None                       # not marked; leave it alone
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    updated = pattern.sub(lambda _m: text, body, count=1)
    if updated == body:
        return "ok"
    if check:
        return "stale"
    path.write_text(updated, encoding="utf-8")
    return "updated"


def _release_assertions(frozen_tree):
    """Assertion total recorded in harness/RELEASE.md, if it describes THIS tree.

    Returns None when there is no release record, or when it was generated on a
    different tree — in which case it says nothing about the run being stamped
    and must not gate it.

    ASSERTIONS, not suite counts. read_run() counts only suites that REPORTED
    (len(oks)), while RELEASE.md's "suites reported" includes skips — 59 against
    61 on this very tree, so a suite-count comparison refuses a legitimate full
    release. The assertion total is the one figure both generators compute the
    same way, because a skipped suite contributes zero to each.
    """
    rel = ROOT / "harness" / "RELEASE.md"
    if not rel.is_file():
        return None
    body = rel.read_text(encoding="utf-8")
    m = re.search(r"tree hash\s+([0-9a-f]{12,64})", body)
    if not m or not frozen_tree or m.group(1)[:12] != frozen_tree[:12]:
        return None
    a = re.search(r"^\s*assertions\s+(\d+)\s*$", body, re.M)
    return int(a.group(1)) if a else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any stanza is stale; write nothing")
    ap.add_argument("--force", action="store_true",
                    help="stamp even if it would NARROW a release-wide record")
    args = ap.parse_args()

    run = read_run()
    text = stanza(run)

    # SCRATCH PROBES MUST NOT BE PUBLISHED AS THE PROJECT'S RESULT.
    #
    # Anything run through run_harness.sh gets stamped, including a one-off
    # `_probe_*.py` written to look at a screenshot. At v213 that put
    # "RUN NOT GREEN — 1 suite(s) failed: _probe_mir.py. 0 assertions passed"
    # into README, START-HERE, HANDOFF and harness/README — four docs claiming
    # the project was failing because a throwaway probe had no assertions.
    #
    # The v212 narrowing guard did not catch it: that only engages when
    # RELEASE.md describes the CURRENT tree, and a scratch probe is usually run
    # mid-change when it does not. This is the cheaper, more general rule —
    # a run whose suite names start with '_' is not a result about the project.
    _scratch = [n for n in run.get("names", []) if n.startswith("_")]
    if _scratch and not args.check:
        print("REFUSED: this run includes scratch probe(s): " + ", ".join(_scratch))
        print("         A throwaway _probe_*.py is not a result about the "
              "project and must not be stamped into the docs.")
        return 0    # not an error: the probe itself ran fine

    # DO NOT LET A ONE-BATCH RUN OVERWRITE A RELEASE-WIDE RECORD.
    #
    # release_run.py already fixed this from one side: it drives run_harness.sh
    # one batch at a time, so the record left behind described only the final
    # batch, and it now rewrites LAST-RUN.txt to cover every batch before
    # re-stamping. But that only holds while the release run is the LAST harness
    # invocation. Any bare `run_harness.sh verify_docs.py` afterwards rewrites
    # LAST-RUN.txt and re-stamps from it — observed at the v212 seal, publishing
    # "36 assertions across 1 suites" beside a RELEASE.md saying 2400 across 61.
    #
    # That is worse than a hand-typed number, not better: it is machine-
    # generated, so it carries exactly the authority this project grants
    # generated figures, and it is wrong. The generated-not-typed rule assumes
    # one generator; there are two, and they can disagree.
    #
    # So: a stamp that would NARROW the record for the SAME tree is refused.
    # --force is the deliberate override. A different tree does not gate at all,
    # because then the release record describes something else.
    if not args.check:
        rel_total = _release_assertions(run.get("tree", ""))
        if rel_total and run["assertions"] < rel_total and not args.force:
            print(f"REFUSED: harness/LAST-RUN.txt records {run['assertions']} "
                  f"assertion(s), but harness/RELEASE.md records {rel_total} on "
                  f"this same tree ({run.get('tree', '')[:12]}).")
            print("         Stamping would replace release-wide evidence with a "
                  "single batch.")
            print("         Re-run the release (harness/release_run.py) so it is "
                  "the LAST invocation, or pass --force.")
            return 1

    stale, touched, unmarked = [], [], []
    for path in TARGETS:
        if not path.is_file():
            continue
        result = apply(path, text, args.check)
        rel = path.relative_to(ROOT)
        if result is None:
            unmarked.append(str(rel))
        elif result == "stale":
            stale.append(str(rel))
        elif result == "updated":
            touched.append(str(rel))

    if unmarked:
        print(f"no {BEGIN} marker (skipped): {', '.join(unmarked)}")
    if args.check:
        if stale:
            print(f"STALE: {', '.join(stale)}")
            print("Run: python3 harness/stamp_docs.py")
            return 1
        print(f"counts are current: {run['assertions']} assertions, "
              f"{run['suites']} suites")
        return 0

    print(f"stamped {run['assertions']} assertions / {run['suites']} suites"
          + (f" into {', '.join(touched)}" if touched else " (already current)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
