"""v131 baseline: posts and rate events

Describes the v131 schema EXACTLY, not current metadata. Autogenerate folded
v132's visibility column and feed indexes in here; they were removed so this
revision matches what is already deployed. An existing v131 database can then be
stamped at this revision and upgraded, instead of being told to create tables it
already has.

  alembic stamp 6aa1de24dda3     # existing v131 database
  alembic upgrade head           # applies v132 onward

Revision ID: 6aa1de24dda3
Revises: 
Create Date: 2026-08-05 13:23:55.896445
"""
from alembic import op
import sqlalchemy as sa


revision = '6aa1de24dda3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skribl_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skribl_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skribl_posts_public_id'), ['public_id'], unique=True)

    op.create_table('skribl_rate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skribl_rate_events', schema=None) as batch_op:
        batch_op.create_index('ix_rate_bucket_key_time', ['bucket', 'key_hash', 'created_at'], unique=False)
        batch_op.create_index('ix_rate_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skribl_rate_events', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_created_at')
        batch_op.drop_index('ix_rate_bucket_key_time')

    op.drop_table('skribl_rate_events')
    with op.batch_alter_table('skribl_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skribl_posts_public_id'))

    op.drop_table('skribl_posts')
    # ### end Alembic commands ###
