"""v135: exact post-media association

Creates the table only. The backfill lives in the SEPARATE v136 revision, and
must: this revision has already been released, so a database that ran it is
already stamped at 86171614cb85. Editing it in place would mean `alembic upgrade
head` sees itself as current and never executes the added code — the upgrade
would silently do nothing for exactly the deployments that need it.

NEVER edit a distributed migration to fix an upgrade. Add a revision.

Revision ID: 86171614cb85
Revises: 88f18e7f844d
Create Date: 2026-08-07 16:00:35.613198
"""
from alembic import op
import sqlalchemy as sa


revision = '86171614cb85'
down_revision = '88f18e7f844d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skribl_post_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_key', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skribl_post_media', schema=None) as batch_op:
        batch_op.create_index('ix_post_media_unique', ['post_id', 'media_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_skribl_post_media_media_key'), ['media_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_skribl_post_media_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skribl_post_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skribl_post_media_post_id'))
        batch_op.drop_index(batch_op.f('ix_skribl_post_media_media_key'))
        batch_op.drop_index('ix_post_media_unique')

    op.drop_table('skribl_post_media')
    # ### end Alembic commands ###
