"""v132: post visibility and feed indexes

Backfills existing posts as 'unlisted' — see the comment on the column. The
application-level default for NEW posts is also 'unlisted'; a client must ask
for 'public' explicitly to appear in a feed.

Revision ID: 88f18e7f844d
Revises: 6aa1de24dda3
Create Date: 2026-08-05 13:24:16.588296
"""
from alembic import op
import sqlalchemy as sa


revision = '88f18e7f844d'
down_revision = '6aa1de24dda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skribl_posts', schema=None) as batch_op:
        # server_default is REQUIRED here: adding a NOT NULL column to a table
        # that already has rows fails without one, and every existing v131 post
        # is such a row. 'unlisted' is the correct backfill — a v131 post was
        # reachable by its share link and listed nowhere, which is exactly what
        # unlisted means. Defaulting to 'public' would retroactively publish
        # every Skribl anyone ever made to the new feed.
        batch_op.add_column(sa.Column('visibility', sa.String(length=16),
                                      nullable=False,
                                      server_default='unlisted'))
        batch_op.create_index('ix_skribl_posts_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_skribl_posts_visibility_created', ['visibility', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skribl_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_skribl_posts_visibility_created')
        batch_op.drop_index('ix_skribl_posts_user_created')
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
